// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZU5BrE-XzdgGf6wvUuqh8WI-I01gPy3A',
    appId: '1:343723762122:web:7b7657d374280c2ae86f33',
    messagingSenderId: '343723762122',
    projectId: 'albumfilmesapp',
    authDomain: 'albumfilmesapp.firebaseapp.com',
    storageBucket: 'albumfilmesapp.firebasestorage.app',
    measurementId: 'G-2MPPPKM1Q4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8VQ-DaypzshHpBzMuQqfIBbnhxBHEbwk',
    appId: '1:343723762122:android:db2d794e2b534c45e86f33',
    messagingSenderId: '343723762122',
    projectId: 'albumfilmesapp',
    storageBucket: 'albumfilmesapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZnV5Wdie652U8lwsfHVOhWKa42nTR8UI',
    appId: '1:343723762122:ios:1fcd31fd5bf4231fe86f33',
    messagingSenderId: '343723762122',
    projectId: 'albumfilmesapp',
    storageBucket: 'albumfilmesapp.firebasestorage.app',
    iosBundleId: 'com.example.albumFilmesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZnV5Wdie652U8lwsfHVOhWKa42nTR8UI',
    appId: '1:343723762122:ios:1fcd31fd5bf4231fe86f33',
    messagingSenderId: '343723762122',
    projectId: 'albumfilmesapp',
    storageBucket: 'albumfilmesapp.firebasestorage.app',
    iosBundleId: 'com.example.albumFilmesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZU5BrE-XzdgGf6wvUuqh8WI-I01gPy3A',
    appId: '1:343723762122:web:e734ec7a8590654fe86f33',
    messagingSenderId: '343723762122',
    projectId: 'albumfilmesapp',
    authDomain: 'albumfilmesapp.firebaseapp.com',
    storageBucket: 'albumfilmesapp.firebasestorage.app',
    measurementId: 'G-NS62EWX08L',
  );
}
